version: 2.1

executors:
  my-runner:
    machine: true
    resource_class: mudlaffp/vagrant

jobs:
  test:
    executor: my-runner
    working_directory: ~/app
    steps:
      - checkout:
          path: ~/app
      - run:
          name: "docker build"
          command: |
            make docker-build


workflows:
  flask-app:
    jobs:
      - test

