# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  test:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/python:3.10.4
        environment:
          QUOTES_DB_URI: postgresql+psycopg2://dbuser:dbpass@localhost:5432/testdb
          FLASK_APP: quotes.py
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_DB: testdb
          POSTGRES_PASSWORD: dbpass
          POSTGRES_USER: dbuser
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    working_directory: ~/app
    steps:
      - checkout:
          path: ~/app
      - run:
          name: "install requirements"
          command: |
            pip install -r requirements.txt
            pip install -r requirements-test.txt
      - run:
          name: "run tests"
          command: |
            flask initdb
            pytest quotes_tests.py

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - test
