version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:current
    working_directory: ~/app
    steps:
      - checkout:
          path: ~/app
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: get docker images
          command: docker image ls
#      - run:
#          name: check pip cache before build
#          command: sudo ls -al /root/.cache/pip
      - run:
          name: "docker build"
          command: |
            export DOCKER_BUILDKIT=1
            make docker-build
      - run:
          name: "docker build2"
          command: |
            export DOCKER_BUILDKIT=1
            make docker-build2
#      - run:
#          name: check pip cache after build
#          command: sudo ls -al /root/.cache/pip
      - run:
          name: get docker images after build
          command: docker image ls
      - run:
          name: check path
          command: |
            ls -al ~/app/pip-cache

workflows:
  flask-app:
    jobs:
      - test
