version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2004:2022.04.1
    working_directory: ~/app
    resource_class: medium
    steps:
      - checkout:
          path: ~/app
      - run:
          name: install dependencies
          command: |
            sudo apt -y update
            sudo apt install -y libvirt-daemon
            echo "after installation libvirt daemon"
            sudo systemctl enable libvirtd
            sudo systemctl start libvirtd
            sudo apt install -y qemu-kvm
      - run:
          name: install and configure podman
          command: |
            sudo apt-get -y update
            sudo apt-get -y install podman
            sudo sh -c "echo $(id -un):100000:200000 >> /etc/subuid"
            sudo sh -c "echo $(id -gn):100000:200000 >> /etc/subgid"
            podman system migrate
            podman ps
      - run:
          name: get docker images
          command: docker image ls
      - run:
          name: get podman images
          command: podman image ls
      - run:
          name: "docker build"
          command: |
            export DOCKER_BUILDKIT=1
            make docker-build
      - run:
          name: check pip cache after docker build
          command: ls -al ./pip-cache
      - run:
          name: "podman build"
          command: |
            export DOCKER_BUILDKIT=1
            export PROJECT_ROOT=$(pwd)
            make podman-build
      - run:
          name: check pip cache after podman build
          command: ls -al ./pip-cache
      - run:
          name: get docker images after build
          command: docker image ls
      - run:
          name: get podman images after build
          command: podman image ls

workflows:
  flask-app:
    jobs:
      - test
